## NUMPY (continuación)

### Operacionies con **Numpy**

In [ ]:
# import numpy library

import numpy as np 

# Create a numpy array

a = np.array([0, 1, 2, 3, 4, 5, 6])
a

In [ ]:
print(type(a))  #tipo de objeto
a.dtype         #tipo de valores de los elementos

#### Se puede acceder a cada elemento por el índice

In [3]:
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[5])
print("a[4]:", a[6])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 5
a[4]: 6


### Asignar valor
#### Podemos cambiar el valor de un un elemento del array. Consideremos el array c:

In [4]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
print(c)

c[0] = 100      #modificamos el primer índice
print(c)

[20  1  2  3  4]
[100   1   2   3   4]


### SLICING

#### Al igual que las listas, podemos hacer slicing en un array de NumPy. El slicing en Python significa tomar los elementos desde un índice dado hasta otro índice dado.

In [5]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[1:8:2])   #imprimimos los elementos pares (empezamos en el índice 1 (que es 2, par) hasta el elemento final (8), con un
#salto de 2)


[2 4 6 8]


### Operaciones de multiplición: **HADAMARK Y PRODUCTO PUNTO**

#### Encontrá el tipo de x usando la función type() ---> **NUMPY ARRAY**

In [7]:
A=np.array([[11,12],[21,22],[31,32]])
type(A)

numpy.ndarray

### Encontrar la forma (**SHAPE**) del array y el número de **DIMENSIONES** del array
#### - shape ---> te dice el tamaño en cada eje: (3, 2) --> (filas, columnas)

#### - ndim ---> te dice cuántas dimensiones tiene el array: 2

In [ ]:
A.shape     #(cantidad de filas, cantidad de columnas)

In [8]:
print(A.ndim)  #cantidad de dimensiones del array
print(A.dtype)  #tipo de datos que forman el array 

2
int64


#### Acceder a la segunda fila completa de la matriz

In [ ]:
B=np.array([[10,20],[30,40],[50,60]])
B[1,]       #1 es el segundo índice (0:primero,1:segundo) y corresponde a la segunda fila. Luego ,vacio) toma todas las columnas

### PRODUCTO HADAMARK (entre vectores o matrices)
#### - El producto de **Hadamard** se puede aplicar a vectores o matrices, siempre que tengan exactamente la misma forma.
#### - Para hacer el producto de **Hadamard** entre dos arrays (vectores o matrices): Deben tener las mismas dimensiones y la misma forma (shape).

In [9]:
A=np.array([[11,12],[21,22],[31,32]])
B=np.array([[10,20],[30,40],[50,60]])
C = A * B
C

array([[ 110,  240],
       [ 630,  880],
       [1550, 1920]])

### PRODUCTO PUNTO - **DOT product**
#### - el número de columnas de A debe ser igual al número de filas de B


In [ ]:
F = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)

G = np.array([[7, 8],
              [9, 10],
              [11, 12]])    # shape (3, 2)
np.dot(F,G)     

#### array([[ 58,  64],    ---------->  ([[ **58** = 1 x 7 + 2 x 9 + 3 x 11,  **64**= 1 x 8 + 2 x 10 + 3 x 12],  
####       [139, 154]])  ----------->  [**139**= 4 x 7 + 5 x 9 + 6 x 11, **154**= 4 x 8 + 5 x 10 + 6 x 12]])